# Generated by Django 5.2.5 on 2025-10-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('max_capacity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
