# Generated by Django 5.2.5 on 2025-10-16 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_tickettype_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booked_by',
            field=models.ManyToManyField(blank=True, related_name='booked_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
